version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: "alertsense/mssql-server-linux"
    environment:
      SA_PASSWORD: "1234"
      ACCEPT_EULA: "Y"